### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by nubonics** [AminHP/gym-anytrading#5]
I would really like to see Binary Options supported by this, and am working myself on trying and completing this (by hiring someone) as I lack the knowledge / am struggling on how to complete this. Nadex is my prefered binary options exchange, however, i can see others benefiting from something such-as iq option

Thank you!

**Comment by AminHP** [comment]
Thank you for your recommendation but actually, I like to keep this project simple and readable for everyone. Adding extra or unnecessary features is not in my plans, at least for now. I prefer to create a codebase that allows people to add everything they want rather than a complete and complex framework.

Good luck!
