### ISSUE TITLE
how to use multi time-frame to create custom  environment

### ISSUE THREAD

**Issue by Masoud1365** [AminHP/gym-anytrading#89]
hi Amin
can we use multi time frame to create custom environment ?
for example, I want to use daily, 4h, 1h time frames for my environment

**Comment by AminHP** [comment]
Hi @Masoud1365 

Yes, it is possible. In order to do so, you need a `Dict` observation space ([here](https://github.com/AminHP/gym-anytrading/blob/master/gym_anytrading/envs/trading_env.py#L37)) with three elements for the daily, 4h, and 1h time frames. You also need to override `TradingEnv._get_observation` ([here](https://github.com/AminHP/gym-anytrading/blob/master/gym_anytrading/envs/trading_env.py#L104)) to return a dictionary of numpy arrays as observation.
